5004 - Docker - fix pipenv version
Recent pipenv version 2022.4.20 dropped support for Python3.6[1].
Installation from Pipfile on Oracle Linux 8 then fails with following error:

  ...
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 577, in parse_extras
       self.line, extras = pip_shims.shims._strip_extras(self.line)
  TypeError: 'NoneType' object is not callable

This commit fixes pipenv version to 2022.4.8, thus resolving the problem.
Default repo on CentOS8 variants contains only python3.6 so upgrade
to python3.8 (or other version) isn't straightforward.

[1] https://github.com/pypa/pipenv/issues/4829