Generator - add missing virtual destructor to Layer class
Detection by clang-tidy:
clang-tidy-14 --use-color -p=build -quiet /home/michal/work/flowtest/tools/ft-generator/src/flow.cpp
/usr/include/c++/11/bits/unique_ptr.h:85:2: error: delete called on 'generator::Layer' that is abstract but has non-virtual destructor [clang-diagnostic-delete-abstract-non-virtual-dtor,-warnings-as-errors]