Generator - use std::shuffle instead of deprecated std::random_shuffle
Clang-tidy detection:
/builds/ZbnBBGDw/2/flowtest/flowtest/tools/ft-generator/src/valuegenerator.cpp:102:7: error: 'random_shuffle<__gnu_cxx::__normal_iterator<unsigned long *, std::vector<unsigned long>>>' is deprecated: use 'std::shuffle' instead [clang-diagnostic-deprecated-declarations,-warnings-as-errors]