ft-replay - Improve MAC address structure
When the MAC address structure is used as a template parameter
of std::optional, it previously triggered following errors:

error: Attempt to free released memory [clang-analyzer-cplusplus.NewDelete]
    delete[] _macPtr;

error: Use of memory after it is freed [clang-analyzer-cplusplus.NewDelete]
    std::memcpy(_macPtr, otherMac._macPtr, MAC_LENGTH);