Generator - clang-tidy-performance: fix move not happening because pcpp::Packet does not have a move constructor
/builds/ZbnBBGDw/1/flowtest/flowtest/tools/ft-generator/src/generator.cpp:52:12: error: passing result of std::move() as a const reference argument; no move will actually happen [performance-move-const-arg,-warnings-as-errors]
        _packet = std::move(packet);
                  ^~~~~~~~~~      ~